### PR TITLE
Add URL Scheme based general plugin with demo project - iOS

### PR DESCRIPTION
**Pull request by liviur**
As discussed - Moving the sample project to the App Plugin examples repository

### CODE REVIEW

**Comment by lomudi** [comment]
@liviur isn't that the same as Full-Screen plugin? shouldn't it be added under https://github.com/applicaster/zapp-plugins-examples/tree/master/FullScreen ?

**Comment by liviur** [comment]
I think in the full screen they created an entire screen while the example I generated is a url scheme handler that is much more generic.

**Comment by liviur** [comment]
This enables also to more conveniently pass parameters on launch of the URL scheme

**Review by lomudi — APPROVED** [review]
💯

**Pull request merged**
